name: Deploy to Netlify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.0'
        
    - name: Remove other .NET versions
      run: |
        sudo rm -rf /usr/share/dotnet/sdk/7.0.*
        sudo rm -rf /usr/share/dotnet/sdk/9.0.*
        sudo rm -rf /usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.*
        sudo rm -rf /usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.*
        sudo rm -rf /usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.*
        sudo rm -rf /usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.*
        
    - name: Verify .NET version
      run: |
        dotnet --version
        dotnet --list-sdks
        
    - name: Restore dependencies
      run: |
        cd TenTen
        dotnet restore TenTenApp.csproj --verbosity normal
        
    - name: Build and publish
      run: |
        cd TenTen
        dotnet publish TenTenApp.csproj -c Release -o publish --verbosity normal
        
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v3.0
      with:
        publish-dir: './TenTen/publish/wwwroot'
        production-branch: main
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
